-- ==========================================
-- JADUI PLACEMENT: Master Database Schema
-- Run this in your Supabase SQL Editor
-- ==========================================

-- 0. User Profiles (Role Management)
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email TEXT UNIQUE NOT NULL,
    full_name TEXT,
    avatar_url TEXT,
    role TEXT DEFAULT 'student' CHECK (role IN ('student', 'admin')),
    -- TPO / Admin fields
    is_shortlisted BOOLEAN DEFAULT false,
    tpo_notes TEXT,
    resume_score INTEGER DEFAULT 0,
    linkedin_url TEXT,
    portfolio_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 1. User System State (Tasks, Roadmap, Notification, AI Context)
CREATE TABLE IF NOT EXISTS public.user_system_state (
    user_id TEXT PRIMARY KEY,
    tasks JSONB DEFAULT '[]',
    roadmap JSONB DEFAULT '[]',
    notifications JSONB DEFAULT '[]',
    skill_gaps JSONB DEFAULT '[]',
    chat_context JSONB DEFAULT '{}',
    chat_history JSONB DEFAULT '[]',
    chat_sessions JSONB DEFAULT '[]',
    active_chat_session_id TEXT,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Resume Files (Parsed raw text)
CREATE TABLE IF NOT EXISTS public.resume_files (
    id TEXT PRIMARY KEY,
    filename TEXT NOT NULL,
    mime_type TEXT,
    candidate_name TEXT,
    parsed_text TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Resume Results (Analysis and scores)
CREATE TABLE IF NOT EXISTS public.resume_results (
    id TEXT PRIMARY KEY,
    file_id TEXT REFERENCES public.resume_files(id),
    role_target TEXT,
    skills JSONB DEFAULT '[]',
    strengths JSONB DEFAULT '[]',
    projects JSONB DEFAULT '[]',
    experience_level TEXT,
    score INTEGER DEFAULT 0,
    summary TEXT,
    overall_feedback TEXT,
    detailed_review JSONB DEFAULT '{}',
    section_reviews JSONB DEFAULT '[]',
    skill_gap JSONB DEFAULT '[]',
    analysis_version TEXT DEFAULT 'v1',
    ai_provider TEXT DEFAULT 'groq',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Interview Sessions (Metadata)
CREATE TABLE IF NOT EXISTS public.interview_sessions (
    id TEXT PRIMARY KEY,
    role TEXT NOT NULL,
    skills JSONB DEFAULT '[]',
    level TEXT,
    interview_type TEXT,
    questions JSONB DEFAULT '[]',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. Interview Answers (Evaluations)
CREATE TABLE IF NOT EXISTS public.interview_answers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id TEXT REFERENCES public.interview_sessions(id),
    question_index INTEGER NOT NULL,
    question TEXT,
    answer TEXT,
    correctness INTEGER DEFAULT 0,
    clarity INTEGER DEFAULT 0,
    relevance INTEGER DEFAULT 0,
    overall INTEGER DEFAULT 0,
    feedback TEXT,
    suggestions JSONB DEFAULT '[]',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 6. Workshops (Training Sessions)
CREATE TABLE IF NOT EXISTS public.workshops (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    title TEXT NOT NULL,
    description TEXT,
    skill_target TEXT,
    curriculum JSONB DEFAULT '[]',
    student_ids UUID[] DEFAULT '{}',
    scheduled_at TIMESTAMP WITH TIME ZONE,
    status TEXT DEFAULT 'suggested' CHECK (status IN ('suggested', 'scheduled', 'completed')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 7. GitHub PR Reviews
CREATE TABLE IF NOT EXISTS public.github_pr_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL,
    repo_owner TEXT NOT NULL,
    repo_name TEXT NOT NULL,
    pr_number INTEGER NOT NULL,
    score INTEGER DEFAULT 0,
    summary TEXT,
    strengths JSONB DEFAULT '[]',
    bugs JSONB DEFAULT '[]',
    security_risks JSONB DEFAULT '[]',
    ideal_code TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 8. GitHub Repository Analyses
CREATE TABLE IF NOT EXISTS public.github_repo_analyses (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id TEXT NOT NULL,
    repo_owner TEXT NOT NULL,
    repo_name TEXT NOT NULL,
    architecture_score INTEGER DEFAULT 0,
    tech_stack JSONB DEFAULT '[]',
    summary TEXT,
    design_patterns JSONB DEFAULT '[]',
    technical_debt JSONB DEFAULT '[]',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Indices for performance
CREATE INDEX IF NOT EXISTS idx_resume_results_file ON public.resume_results(file_id);
CREATE INDEX IF NOT EXISTS idx_interview_answers_session ON public.interview_answers(session_id);
CREATE INDEX IF NOT EXISTS idx_workshops_status ON public.workshops(status);
CREATE INDEX IF NOT EXISTS idx_github_reviews_user ON public.github_pr_reviews(user_id);
CREATE INDEX IF NOT EXISTS idx_github_repo_analyses_user ON public.github_repo_analyses(user_id);

-- ==========================================
-- MIGRATION: Add missing columns to profiles
-- Safe to run on existing databases
-- ==========================================
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS is_shortlisted BOOLEAN DEFAULT false;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS tpo_notes TEXT;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS resume_score INTEGER DEFAULT 0;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS linkedin_url TEXT;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS portfolio_url TEXT;
